name: Build & Deploy Tickr Premarket Evaluation
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Tickr Premarket Evaluation Python app to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }} # IP address of the server you wish to ssh into....
          key: ${{ secrets.SSH_KEY }} # Private or Public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you wish to ssh into
          passphrase: ${{ secrets.SSH_PASSPHRASE }} # Passphrase for ssh key
          fingerprint: ${{ secrets.SSH_FINGERPRINT }} # Fingerprint for ssh key
          script:
            mkdir tickr-premarket
            cd "tickr-premarket"
            git clone git@github.com:quan005/Tickr-premarket-evaluation.git
            echo 'Deployment Successful'
            