name: Run Tickr Premarket Evaluation on a Cron Schedule
on:
  schedule:
    - cron: '30 15 * * 1-5'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ssh into server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }} # IP address of the server you wish to ssh into
          key: ${{ secrets.SSH_KEY }} # Private or Public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you wish to ssh into
          command_timeout: 300m
          script: |
            cd "tickr-premarket/"
            cd "Tickr-premarket-evaluation/"
            python3 pre_market.py
            echo 'Tickr Premarket Evaluation Complete'